name: rf-practical
channels:
  - conda-forge
dependencies:
  - cartopy
  - colorama
  - dill
  - geographiclib
  - joblib
  - matplotlib
  - numpy
  - obspy>=1.3.1
  - OWSLib
  - pandas
  - pip
  - plotly
  - prov
  - psutil
  - h5py
  - pytest
  - python>=3.10
  - scipy
  - tqdm
  - flake8
  - pyvista
  - pyyaml
  - jupyter
  - pip:
    - global-land-mask
    - sphinx<6.0
    - pydata-sphinx-theme
    - sphinx-copybutton
    - sphinx-gallery
    - jinja2<3.1
    - pyglimer